default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods

    sync_code_signing(type: "appstore")
    build_app(workspace: "Pantries.xcworkspace", scheme: "Pantries")
    upload_to_testflight
  end
end
